// <auto-generated />
using EstudoDotNetCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EstudoDotNetCore.Migrations
{
    [DbContext(typeof(PessoaDbContext))]
    partial class PessoaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EstudoDotNetCore.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PES_ID");

                    b.Property<int>("Idade")
                        .HasColumnName("PES_IDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("PES_NOME")
                        .HasMaxLength(50);

                    b.Property<string>("Observacoes")
                        .HasColumnName("PES_OBSERVACOES")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("PES_PESSOAS");
                });
#pragma warning restore 612, 618
        }
    }
}
